export const INDIAN_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal"
];

export const ODISHA_DISTRICTS = [
  "Angul",
  "Balangir",
  "Balasore",
  "Bargarh",
  "Bhadrak",
  "Boudh",
  "Cuttack",
  "Deogarh",
  "Dhenkanal",
  "Gajapati",
  "Ganjam",
  "Jagatsinghpur",
  "Jajpur",
  "Jharsuguda",
  "Kalahandi",
  "Kandhamal",
  "Kendrapara",
  "Kendujhar (Keonjhar)",
  "Khordha",
  "Koraput",
  "Malkangiri",
  "Mayurbhanj",
  "Nabarangpur",
  "Nayagarh",
  "Nuapada",
  "Puri",
  "Rayagada",
  "Sambalpur",
  "Subarnapur (Sonepur)",
  "Sundargarh"
];

export const ODISHA_DISTRICT_BLOCKS: Record<string, string[]> = {
  "Khordha": ["Bhubaneswar", "Jatni", "Khurda", "Begunia", "Bolagarh", "Chilika", "Tangi", "Balianta", "Balipatna"],
  "Cuttack": ["Cuttack City", "Athagarh", "Banki", "Baramba", "Niali", "Salepur", "Tangi-Choudwar", "Mahanga", "Kantapada"],
  "Ganjam": ["Brahmapur", "Chatrapur", "Hinjilicut", "Aska", "Bhanjanagar", "Sorada", "Polasara", "Khallikote", "Chikiti"],
  "Puri": ["Puri Town", "Satyabadi", "Pipili", "Nimapara", "Konark", "Kakatpur", "Astaranga", "Brahmagiri", "Krushnaprasad"],
  "Balasore": ["Balasore Town", "Jaleswar", "Soro", "Basta", "Baliapal", "Nilagiri", "Oupada", "Khantapada", "Remuna"],
  "Sundargarh": ["Rourkela", "Sundargarh Town", "Rajgangpur", "Biramitrapur", "Bonai", "Kutra", "Kuanrmunda", "Lahunipara", "Bargaon"]
};
